name: PHPUnit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, dom, xml, xmlwriter, pdo, pdo_mysql, pdo_sqlite
          coverage: none

      - name: Show versions
        run: |
          php -v
          mkdir -p Test/tools
          curl -L https://phar.phpunit.de/phpunit-9.phar -o Test/tools/phpunit.phar
          php Test/tools/phpunit.phar --version

      - name: Run PHPUnit
        run: php Test/tools/phpunit.phar --configuration Test/phpunit.xml
