name: Ejecutar Pruebas PHPUnit

on:
  pull_request:
    branches:
      - main

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Descargar PHPUnit
        run: |
          mkdir -p Test/tools
          wget https://phar.phpunit.de/phpunit-9.phar -O Test/tools/phpunit.phar
          chmod +x Test/tools/phpunit.phar

      - name: Ejecutar pruebas
        run: php Test/tools/phpunit.phar --configuration Test/phpunit.xml